language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - gfortran
    - clang
    - libz-dev
    - libbz2-dev
    - libblas-dev
    - liblapack-dev
    - libarpack2-dev
    - libnetcdf-dev
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev

matrix:
  include:
    - { os: linux }

sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew tap homebrew/science;
      brew update;
      brew install netcdf fftw gcc;
    fi

install:
    - source install_python.sh
    - conda install -c http://ambermd.org/downloads/ambertools-rc/conda ambertools --yes

script:
    - tleap -h
    - sqm -h
    # - sander -h # sander -h exit 1, ack
    - cpptraj -h
    - python -c "import parmed; print(parmed)"
    - python -c "import sander; print(sander)"
    - python -c "import pytraj; print(pytraj)"
    - python -c "import nglview; print(nglview)"   

notifications:
  email: false
